
## You can use this file, or make multiple files, to create a conda environment for this project:
##   conda env create -f environment.yml
name: {{cookiecutter.project_name}}
channels:
  - conda-forge
  - bioconda
  - defaults
